### ISSUE TITLE
Error with Typo3 11 and PHP 8

### ISSUE THREAD

**Issue by tomashavner** [FriendsOfTYPO3/jumpurl#33]
Hi,

Jumpurl generates a warning in Typo3 11.5.15 and PHP 8. It's "typo3.sol.lu.se/typo3conf/ext/jumpurl/Classes/Middleware/JumpUrlHandler.php", line 60: 
$jumpUrl = (string)$request->getQueryParams()['jumpurl'] ?? '';" 
that generates a missing array key warning. Removing the (string) fixes the problem. 

Kind regards

Tomas

**Comment by bmack** [comment]
Hey @tomashavner ,

I guess this needs to be:
`$jumpUrl = (string)($request->getQueryParams()['jumpurl'] ?? '');"`

**Comment by tomashavner** [comment]
Yes, works!

**Comment by bmack** [comment]
see #35 which fixes the problem, but the PR needs work

**Comment by mediaessenz** [comment]
It would be really nice to see a release with this fix soon, since it crashes the frontend in development context.

**Comment by mediaessenz** [comment]
Since this issues was solved with the merge of https://github.com/FriendsOfTYPO3/jumpurl/pull/39 , it can be closed.

Btw.: Could someone create a 8.1.9 release for TER as well?

**Comment by bmack** [comment]
8.1.0, however I think the TER upload still does not work yet.

**Comment by mediaessenz** [comment]
Of corse 1.8.0.

Why do you think TER upload does not work yet?

**Comment by bmack** [comment]
<img width="1226" alt="Screenshot 2023-04-04 at 10 13 37" src="https://user-images.githubusercontent.com/165630/229730328-51289c8e-435e-4db0-84ca-2f54887570cc.png">

from extensions.typo3.org
